query GetPlanetById {
  planet(id: 12) {
    id
    name
    climate
    latitude
    longitude
    population
    terrain
    characters {
      id
      name
    }
    starships {
      id
      name
    }
  }
}

query GetAllPlanets {
  planets {
    id
    name
    climate
    latitude
    longitude
    population
    terrain
    characters {
      id
      name
    }
    starships {
      id
      name
    }
  }
}

mutation CreatePlanet {
  createPlanet(
    createPlanetInput: {
      climate: "Temperate"
      latitude: 22.0
      longitude: 23.0
      name: "Earth"
      population: 1000000000
      terrain: "Varied"
    }
  ) {
    id
  }
}

mutation RemovePlanet {
  removePlanet(id: 16) {
    id
  }
}

mutation UpdatePlanet {
  updatePlanet(updatePlanetInput: { id: 12, name: "Super Venus" }) {
    id
  }
}

query CalculateDistanceToStarship {
  calculateDistanceToStarship(
    calculateDistanceToStarshipInput: { starshipId: 13, planetId: 12 }
  ) {
    distanceInMeters
  }
}

query GetStarshipById {
  starship(id: 11) {
    id
    name
    model
    cargoCapacity
    currentPlanet {
      id
      name
    }
    passengers {
      id
      name
    }
    latitude
    longitude
  }
}

query GetAllStarships {
  starships {
    id
    name
    model
    cargoCapacity
    currentPlanet {
      id
      name
    }
    passengers {
      id
      name
    }
    latitude
    longitude
    currentPlanet {
      id
      name
    }
  }
}

mutation CreateStarship {
  createStarship(
    createStarshipInput: {
      cargoCapacity: 1000
      currentPlanetId: 12
      latitude: 22.0
      longitude: 23.0
      model: "A-Wing"
      name: "Star Destroyer"
    }
  ) {
    id
    currentPlanet {
      id
      name
    }
  }
}

mutation RemoveStarship {
  removeStarship(id: 18) {
    id
    name
  }
}

mutation UpdateStarship {
  updateStarship(
    updateStarshipInput: {
      cargoCapacity: 5
      currentPlanetId: 15
      id: 14
      latitude: 33.0
      longitude: 44.0
      model: "B-Wing"
      name: "Death Star"
    }
  ) {
    id
    currentPlanet {
      name
    }
  }
}

query GetCharacterById {
  character(id: 11) {
    id
    name
    currentLocationId
    sensitivityToTheForce
    species
    starshipId
    currentLocation {
      id
      name
    }
    starship {
      id
      name
    }
  }
}

query GetAllCharacters {
  characters {
    id
    name
    sensitivityToTheForce
    species
    currentLocation {
      id
      name
    }
    starshipId
    starship {
      name
      id
    }
  }
}

mutation DisembarkCharacter {
  disembarkCharacter(disembarkCharacterInput: { characterId: 11 }) {
    id
    name
  }
}

mutation EmbarkCharacter {
  embarkCharacter(embarkCharacterInput: { starshipId: 13, characterId: 13 }) {
    id
    name
  }
}

mutation RelocateCharacter {
  relocateCharacter(relocateCharacterInput: { characterId: 11, planetId: 12 }) {
    id
    currentLocationId
    name
  }
}

mutation CreateCharacter {
  createCharacter(
    createCharacterInput: {
      currentLocationId: 12
      name: "John Doe"
      sensitivityToTheForce: "High"
      species: "Human"
    }
  ) {
    id
  }
}

mutation RemoveCharacter {
  removeCharacter(id: 15) {
    id
  }
}

mutation UpdateCharacter {
  updateCharacter(
    updateCharacterInput: {
      currentLocationId: 14
      id: 11
      name: "Leia"
      sensitivityToTheForce: "Low"
      species: "Alien"
    }
  ) {
    id
    currentLocationId
    name
    sensitivityToTheForce
    species
  }
}
